"""Remove all files generated by the ML pipeline (data/processed, outputs)."""

import os
import shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

DIRS_TO_CLEAN = [
    os.path.join(SCRIPT_DIR, "data", "processed"),
    os.path.join(SCRIPT_DIR, "outputs"),
]


def clean():
    removed = 0
    for d in DIRS_TO_CLEAN:
        if os.path.isdir(d):
            n = sum(len(files) for _, _, files in os.walk(d))
            shutil.rmtree(d)
            removed += n
            print(f"Removed {d}/ ({n} files)")
        else:
            print(f"Skipped {d}/ (not found)")

    print(f"\nDone — {removed} files removed.")


if __name__ == "__main__":
    clean()
